spring.application.name=drifiting-bottle

spring.datasource.url=jdbc:postgresql://db.udhtnutizoxfbfvhisop.supabase.co:5432/postgres?user=postgres&password=Saivishwa@13
spring.datasource.username=postgres
spring.datasource.password=Saivishwa@13
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Project-name : Drifting-bottle
#Database Password: Saivishwa@13